server:
  port: 9015

spring:
  datasource:
    url: jdbc:mysql://localhost/examinationdb
    username: root
    password: Chris@24
  jpa:
    show_sql: true
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
        
examination:
  api:
    numberOfExaminationQuestion: 3